# Generated by Django 4.2.5 on 2024-04-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_notes_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='file',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
        migrations.AddField(
            model_name='notes',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='notes',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
